// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ObtenerDetallesProyecto(arg1) {
  return window['go']['main']['App']['ObtenerDetallesProyecto'](arg1);
}

export function ObtenerProyectosRecientes() {
  return window['go']['main']['App']['ObtenerProyectosRecientes']();
}
