// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function ObtenerDetallesProyecto(arg1:number):Promise<store.ProyectoDetalle>;

export function ObtenerProyectosRecientes():Promise<Array<store.ProyectoResumen>>;
