// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarEscena(arg1, arg2) {
  return window['go']['main']['App']['ActualizarEscena'](arg1, arg2);
}

export function CambiarEstadoEscena(arg1, arg2, arg3) {
  return window['go']['main']['App']['CambiarEstadoEscena'](arg1, arg2, arg3);
}

export function ConectarEscenas(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConectarEscenas'](arg1, arg2, arg3, arg4);
}

export function CrearEscena(arg1, arg2, arg3) {
  return window['go']['main']['App']['CrearEscena'](arg1, arg2, arg3);
}

export function DesconectarEscenas(arg1, arg2) {
  return window['go']['main']['App']['DesconectarEscenas'](arg1, arg2);
}

export function EliminarEscena(arg1, arg2) {
  return window['go']['main']['App']['EliminarEscena'](arg1, arg2);
}

export function EliminarProyecto(arg1) {
  return window['go']['main']['App']['EliminarProyecto'](arg1);
}

export function GuardarProyecto(arg1) {
  return window['go']['main']['App']['GuardarProyecto'](arg1);
}

export function ListarProyectos() {
  return window['go']['main']['App']['ListarProyectos']();
}

export function MoverEscena(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoverEscena'](arg1, arg2, arg3, arg4);
}

export function ObtenerProyecto(arg1) {
  return window['go']['main']['App']['ObtenerProyecto'](arg1);
}

export function ReordenarEscena(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReordenarEscena'](arg1, arg2, arg3);
}
