// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ActualizarEscena(arg1:string,arg2:domain.Escena):Promise<void>;

export function CambiarEstadoEscena(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConectarEscenas(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Conexion>;

export function CrearEscena(arg1:string,arg2:string,arg3:string):Promise<domain.Escena>;

export function DesconectarEscenas(arg1:string,arg2:string):Promise<void>;

export function EliminarEscena(arg1:string,arg2:string):Promise<void>;

export function EliminarProyecto(arg1:string):Promise<void>;

export function GuardarProyecto(arg1:domain.Proyecto):Promise<void>;

export function ListarProyectos():Promise<Array<domain.ProyectoResumen>>;

export function MoverEscena(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function ObtenerProyecto(arg1:string):Promise<domain.Proyecto>;

export function ReordenarEscena(arg1:string,arg2:string,arg3:number):Promise<void>;
